# <div style="text-align:center"> <font color=#337ab7>NumPy </font></div>

<div style="text-align : right">Rahul Reddy Gajjada</div>

## <span style="color:#337ab7"> Starting with NumPy... </span>
1. NumPy’s main object is the <span style="color:#337ab7">homogeneous multidimensional array.</span>
2. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. 
3. In NumPy dimensions are called <span style="color:#337ab7">axes</span>.

### <span style="color:#337ab7">Example:</span>

In [151]:
[[ 1., 0., 0.], 
 [ 0., 1., 2.]]

[[1.0, 0.0, 0.0], [0.0, 1.0, 2.0]]

 
The above array has 2 axes. <br/>
Guess the length of each axis !

NumPy’s array class is called <span style="color:#337ab7">__ndarray__</span>. It is also known by the alias <span style="color:#337ab7">__array__</span>. <br/>Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality. 

###  <span style="color:#337ab7">The important attributes of an ndarray object are:</span>

<span style="color:#337ab7"><b>ndarray.ndim : </b></span><br>
    the number of axes (dimensions) of the array.<br/>
<span style="color:#337ab7"><b>ndarray.shape :</b></span><br> 
the dimensions of the array. <br/>This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). <br/>
<span style="color:#337ab7"><b>ndarray.size : </b></span><br/>
 the total number of elements of the array. This is equal to the product of the elements of shape.<br/>
<span style="color:#337ab7"><b>ndarray.dtype : </b></span><br/>
an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types.<br/> Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples. <br/>
<span style="color:#337ab7"><b>ndarray.itemsize :</b></span><br/>
the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to <i>ndarray.dtype.itemsize</i>.<br/>
<span style="color:#337ab7"><b>ndarray.data : </b></span><br/>
the buffer containing the actual elements of the array.<br/>

### <span style="color:#337ab7">Example</span>

In [1]:
import numpy as np

a = np.arange(15).reshape(3,5)
print(a)
a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.itemsize)
print(a.size)
print(type(a))

(3, 5)
2
int32
4
15
<class 'numpy.ndarray'>


In [4]:
b = np.array([10,20.5,30])
print(type(b), b.dtype)
b

<class 'numpy.ndarray'> float64


array([10. , 20.5, 30. ])

In [5]:
a = np.array(1,2,3,4)    # WRONG 

ValueError: only 2 non-keyword arguments accepted

<span style="color:#337ab7"><b>array</b></span> transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [6]:
np.array([(1.5,2,3), (4,5,6)])

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [7]:
#The type of array can be explicitly specified
np.array( [ [1,2], [3,4] ], dtype=complex )

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

## <span style="color:#337ab7">Zeros, ones and empty</span>
The function <span style="color:#337ab7">zeros</span> creates an array full of zeros, the function <span style="color:#337ab7">ones</span> creates an array full of ones, and the function <span style="color:#337ab7">empty</span> creates an array whose initial content is random and depends on the state of the memory. <br>By default, the dtype of the created array is <span style="color:#337ab7">float64</span>.

In [8]:
print(np.zeros((3,4)))
print('-------------')
print(np.ones((2,3), dtype=np.int16))
print('-------------')
print(np.empty((3,3))) # As uninitialized, the output may vary

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-------------
[[1 1 1]
 [1 1 1]]
-------------
[[3.56195639e-318 2.88462678e-316 6.45707041e-317]
 [7.38081546e-315 7.38081546e-315 4.83818487e-316]
 [4.83819001e-316 4.83819515e-316 4.34584738e-311]]


### <span style="color:#337ab7">Linspace</span>
Return evenly spaced numbers over a specified interval

In [9]:
np.arange( 0, 2, 0.3 ) 

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [10]:
np.linspace( 0, 2, 9 )

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [20]:
# Linspace can be used to evaluate a function with lots of datapoints
from numpy import pi
x = np.linspace( 0, 2*pi, 100 )
f = np.sin(x)
print(f[1:20])

[0.06342392 0.12659245 0.18925124 0.25114799 0.31203345 0.37166246
 0.42979491 0.48619674 0.54064082 0.59290793 0.64278761 0.69007901
 0.73459171 0.77614646 0.81457595 0.84972543 0.88145336 0.909632
 0.93414786]


## <span style="color:#337ab7">Basic Operations</span>
Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [12]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )  #b = [0, 1, 2, 3]

c = a-b
print("Subtraction : " ,c)

print("Exponential : ", b**2)

print("Sin operation : ", 10*np.sin(a))

print(a<35)

Subtraction :  [20 29 38 47]
Exponential :  [0 1 4 9]
Sin operation :  [ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]


The product operator <span style="color:#337ab7">*</span> operates <span style="color:#337ab7">elementwise</span> in NumPy arrays. <br> 
The matrix product can be performed using the<span style="color:#337ab7">@</span> operator (in python >=3.5) or the <span style="color:#337ab7">dot</span> function or method:

In [13]:
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0], [3,4]] )

# Element wise product
print(A * B ) 
print("========")

# Matrix Product
print(A @ B)
print("========")

#Matrix Product using dot function 
print(A.dot(B))


[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

In [14]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
print(a)
print(b)
a *= 3
print(a)
b += a
print(b)

[[1 1 1]
 [1 1 1]]
[[0.14145349 0.04908612 0.42551686]
 [0.64158204 0.86440521 0.12566562]]
[[3 3 3]
 [3 3 3]]
[[3.14145349 3.04908612 3.42551686]
 [3.64158204 3.86440521 3.12566562]]


When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [15]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
print("dtype of a :", a.dtype.name)
print("dtype of b :", b.dtype.name)
c = a+b
print(c)
print("dtype of c :", c.dtype.name)

d = np.exp(c*1j)
print(d)
print("dtype of d :",d.dtype.name)


dtype of a : int32
dtype of b : float64
[1.         2.57079633 4.14159265]
dtype of c : float64
[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]
dtype of d : complex128


Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [16]:
a = np.random.random((2,3))
print(a)
print("Sum : ", a.sum())
print("Min : ", a.min())
print("Max : ", a.max())


[[0.97188922 0.95581759 0.88274412]
 [0.36705603 0.13782805 0.99554263]]
Sum :  4.310877650387778
Min :  0.1378280531222147
Max :  0.9955426347966528


By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. 
However, by specifying the <span style="color:#337ab7">axis</span> parameter you can apply an operation along the specified axis of an array:

In [17]:
b = np.arange(12).reshape(3,4)
print(b)

print("Sum : ",b.sum(axis=0))  # Sum of each column

print("Min : ",b.min(axis=1))  # Min of each column

print("CumSum : ") ;print(b.cumsum(axis=1))  # cumulative sum along each row


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Sum :  [12 15 18 21]
Min :  [0 4 8]
CumSum : 
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


## <span style="color:#337ab7">Universal Functions</span>

NumPy provides familiar mathematical functions such as sin, cos, and exp. <br>
In NumPy, these are called <span style="color:#337ab7">“universal functions”(ufunc)</span>. <br>
Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [28]:
B = np.arange(3)
print("B: ",B)
print("Exp: ",np.exp(B))
print("Sqrt :",np.sqrt(B))
C = np.array([2., -1., 4.])
print("Add: ",np.add(B, C))

B:  [0 1 2]
Exp:  [1.         2.71828183 7.3890561 ]
Sqrt : [0.         1.         1.41421356]
Add:  [2. 0. 6.]


## <span style="color:#337ab7">Indexing, Slicing and Iterating</span>

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [43]:
a = np.arange(10)**3
print(a)
print(a[2])
print(a[2:6])
a[:6:2] = -100    # equivalent to a[0:6:2] from start to position 6, exclusive, set every 2nd element to -100
print(a)
print(a[ : :-1] )
# Iterating using a for loop
for i in a:
    print(i**(1/2))

[  0   1   8  27  64 125 216 343 512 729]
8
[  8  27  64 125]
[-100    1 -100   27 -100  125  216  343  512  729]
[ 729  512  343  216  125 -100   27 -100    1 -100]
nan
1.0
nan
5.196152422706632
nan
11.180339887498949
14.696938456699069
18.520259177452132
22.627416997969522
27.0


C:\Users\sairam\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: RuntimeWarning: invalid value encountered in power


Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [58]:
B = np.arange(20).reshape(5,4)
print("-------------- ")
print(B)
print("-------------- ")
print(B[2,3])
print("-------------- ")
print(B[0:5, 1])    # each row in the second column of B
print("-------------- ")
print(B[ : ,1] )    # equivalent to the previous example
print("-------------- ")
print(b[1:3, : ])   # each column in the second and third row of B

-------------- 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
-------------- 
11
-------------- 
[ 1  5  9 13 17]
-------------- 
[ 1  5  9 13 17]
-------------- 
[[ 4  5  6  7]
 [ 8  9 10 11]]


When fewer indices are provided than the number of axes, the missing indices are considered complete slices:

In [61]:
print(b[-1])  # the last row. Equivalent to b[-1,:]

[ 8  9 10 11]


The expression within brackets in <b>b[i]</b> is treated as an <b>i</b> followed by as many instances of <b>:</b> as needed to represent the remaining axes. <br>
NumPy also allows you to write this using dots as <b>b[i,...]</b>.

The <b>dots (...) </b>represent as many colons as needed to produce a complete indexing tuple. <br>
For example, if x is an array with 5 axes, then

x[1,2,...] is equivalent to x[1,2,:,:,:],<br>
x[...,3] to x[:,:,:,:,3] and <br>
x[4,...,5,:] to x[4,:,:,5,:].

In [67]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])
print(c)
print("--------")
print(c[1,...])   # same as c[1,:,:] or c[1]
print("--------")
print(c[...,2])   # same as c[:,:,2]

[[[  0   1   2]
  [ 10  12  13]]

 [[100 101 102]
  [110 112 113]]]
--------
[[100 101 102]
 [110 112 113]]
--------
[[  2  13]
 [102 113]]


Iterating over multidimensional arrays is done with respect to the first axis:

In [69]:
b = np.arange(20).reshape(5,4)
for row in b:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]


However, if one wants to perform an operation on each element in the array, one can use the <b>flat</b> 
attribute <br>which is an iterator over all the elements of the array:

In [71]:
b = np.arange(10).reshape(5,2)
for element in b.flat:
    print(element)

0
1
2
3
4
5
6
7
8
9


## <span style="color:#337ab7">Shape Manipulation</span>
An array has a shape given by the number of elements along each axis:

In [72]:
a = np.floor(10*np.random.random((3,4)))
print(a)
print("Shape : ", a.shape)

[[8. 2. 7. 8.]
 [3. 9. 4. 6.]
 [7. 7. 5. 2.]]
Shape :  (3, 4)


The shape of an array can be changed with various commands. <br>
Note that the following three commands all return a <b>modified array</b>, but do not change the original array:

In [78]:
a = np.floor(10*np.random.random((3,4)))
print(a);print("------------")
print(a.shape)
print("------------")
print(a.ravel())       # returns the array, flattened
print("------------")
print(a.reshape(6,2))  # returns the array with a modified shape
print("------------")
print(a.T)             # returns the array, transposed
print("------------")
print(a.T.shape)

[[6. 5. 3. 9.]
 [6. 6. 5. 0.]
 [3. 4. 3. 1.]]
------------
(3, 4)
------------
[6. 5. 3. 9. 6. 6. 5. 0. 3. 4. 3. 1.]
------------
[[6. 5.]
 [3. 9.]
 [6. 6.]
 [5. 0.]
 [3. 4.]
 [3. 1.]]
------------
[[6. 6. 3.]
 [5. 6. 4.]
 [3. 5. 3.]
 [9. 0. 1.]]
------------
(4, 3)


The <span style="color:#337ab7">reshape</span> function returns its argument with a modified shape, whereas the <span style="color:#337ab7">ndarray.resize </span> method modifies the array itself:

In [89]:
a = np.array([[ 2.,  8.,  0.,  6.],[ 4.,  5.,  1.,  1.],[ 8.,  9.,  3.,  6.]])
print(a)
print("-----------------")
a.resize((2,6))
print(a)

[[2. 8. 0. 6.]
 [4. 5. 1. 1.]
 [8. 9. 3. 6.]]
-----------------
[[2. 8. 0. 6. 4. 5.]
 [1. 1. 8. 9. 3. 6.]]


If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:

In [95]:
a = np.array([[ 2.,  8.,  0.,  6.],[ 4.,  5.,  1.,  1.],[ 8.,  9.,  3.,  6.]])
print(a)
print("-----------------")
print(a.reshape(2,-1))

[[2. 8. 0. 6.]
 [4. 5. 1. 1.]
 [8. 9. 3. 6.]]
-----------------
[[2. 8. 0. 6. 4. 5.]
 [1. 1. 8. 9. 3. 6.]]


In [ ]:
#random module of numpy is used to generate various random sequences.
#randn is used to simulate standard normal distribution.
#loadtxt is used to read data from a text file or any input data stream.

## <span style="color:#337ab7">Stacking and splitting different arrays</span>

* Two or more arrays can be joined vertically using the generic vstack method.
* Two or more arrays can be joined horizontally using the generic hstack method.
* Arrays can be split vertically using the generic vsplit method
* Arrays can be split horizontally using the generic hsplit method.


In [117]:
#random module of numpy is used to generate various random sequences.

a = np.floor(10*np.random.random((2,2)))
b = np.eye(2)
print(a)
print("------------")
print(b)
print("------------")
c = np.vstack((a,b))
print(c)
print("------------")
d = np.hstack((a,b))
print(d)

[[1. 9.]
 [6. 6.]]
------------
[[1. 0.]
 [0. 1.]]
------------
[[1. 9.]
 [6. 6.]
 [1. 0.]
 [0. 1.]]
------------
[[1. 9. 1. 0.]
 [6. 6. 0. 1.]]


In [123]:
#Splitting
a = np.floor(10*np.random.random((2,12)))
print(a)
print("------------")

print(np.hsplit(a,3)) # Split a into 3
print("------------")

print(np.hsplit(a,(3,6)))   # Split a after the third and the sixth column

[[6. 3. 9. 2. 1. 2. 7. 7. 6. 6. 7. 5.]
 [6. 4. 5. 6. 8. 6. 5. 2. 1. 7. 6. 5.]]
------------
[array([[6., 3., 9., 2.],
       [6., 4., 5., 6.]]), array([[1., 2., 7., 7.],
       [8., 6., 5., 2.]]), array([[6., 6., 7., 5.],
       [1., 7., 6., 5.]])]
------------
[array([[6., 3., 9.],
       [6., 4., 5.]]), array([[2., 1., 2.],
       [6., 8., 6.]]), array([[7., 7., 6., 6., 7., 5.],
       [5., 2., 1., 7., 6., 5.]])]


## <span style="color:#337ab7">Broadcasting in Numpy</span>

* You can perform arithmetic directly on NumPy arrays, such as addition and subtraction.<br>
* For example, two arrays can be added together to create a new array where the values at each index are added together. <br>
* Strictly, arithmetic may only be performed on arrays that have the same dimensions and dimensions with the same size.<br>
* This means that a one-dimensional array with the length of 10 can only perform arithmetic with another one-dimensional array with the length 10.<br>
* However, NumPy provides a built-in workaround to allow arithmetic between arrays with differing sizes.

> Broadcasting solves the problem of arithmetic between arrays of differing shapes by in effect replicating the smaller array<br> along the last mismatched dimension. <br> NumPy does not actually duplicate the smaller array; instead, it makes memory and computationally efficient use of existing structures in memory that in effect achieve the same result

In [127]:
a = np.array([1, 2, 3])
print(a); print("---------")
b = 2
print(b); print("---------")
c = a + b
print(c)

[1 2 3]
---------
2
---------
[3 4 5]


In [128]:
A = np.array([[1, 2, 3], [1, 2, 3]])
print(A)
print("---------")
b = np.array([1, 2, 3])
print(b)
print("---------")
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
---------
[1 2 3]
---------
[[2 4 6]
 [2 4 6]]


In [129]:
A = np.array([[1, 2, 3], [1, 2, 3]])
print(A.shape)
print("---------")
b = np.array([1, 2])
print(b.shape)
print("---------")
C = A + b
print(C)

(2, 3)
---------
(2,)
---------


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

## <span style="color:#337ab7">Linear Algebra</span>
NumPy package contains <span style="color:#337ab7">numpy.linalg</span> module that provides all the functionality required for linear algebra. <br>Some of the important functions in this module are :
* dot : Dot product of the two arrays
* determinant : Computes the determinant of the array
* matmul : Matrix product of the two arrays
* solve :  Solves the linear matrix equation
* inv : Finds the multiplicative inverse of the matrix

In [130]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
 
# Rank of a matrix
print("Rank of A:", np.linalg.matrix_rank(A))
 
# Trace of matrix A
print("\nTrace of A:", np.trace(A))
 
# Determinant of a matrix
print("\nDeterminant of A:", np.linalg.det(A))
 
# Inverse of matrix A
print("\nInverse of A:\n", np.linalg.inv(A))
 
print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(A, 3))

Rank of A: 3

Trace of A: 11

Determinant of A: -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]


In [132]:
a = np.diag((1, 2, 3))
print("Array is :",a)
 
# calculating an eigen value using eig() function for a square array
c, d = np.linalg.eig(a)
 
print("Eigen value is :",c)
print("Eigen vectors is :",d)

Array is : [[1 0 0]
 [0 2 0]
 [0 0 3]]
Eigen value is : [1. 2. 3.]
Eigen vectors is : [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [133]:
a = np.array([[1, 2], [3, 4]])
b = np.array([8, 18])
 
print(("Solution of linear equations:", 
      np.linalg.solve(a, b)))

('Solution of linear equations:', array([2., 3.]))


## <span style="color:#337ab7">Misc...</span>

In [134]:
filedata = np.genfromtxt('sampleData.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[100 120 140 180 150 210 300 320 174  56  90]
